#!/usr/bin/env bash
# Attendance Pro - one-click installer (macOS / Linux)
set -e
cd "$(dirname "$0")"

echo "================================================"
echo "   ATTENDANCE PRO - ONE CLICK INSTALLER"
echo "   Your high-class attendance system"
echo "================================================"

# 1. Node.js
echo "[1/4] Checking Node.js..."
if ! command -v node >/dev/null 2>&1; then
  echo "[X] Node.js is NOT installed. Please install Node.js 18+ from https://nodejs.org"
  exit 1
fi
echo "    OK - Node.js $(node -v) found"

# 2. Dependencies
echo "[2/4] Installing dependencies (this may take a minute)..."
npm install --no-audit --no-fund || { echo "[X] npm install failed"; exit 1; }
echo "    OK - Dependencies installed"

# 3. Database
echo "[3/4] Database configuration"
if [ -f .env ]; then
  echo "    OK - .env found. Keeping existing configuration."
else
  echo "   Enter your CockroachDB connection string."
  echo "   (cloud example) postgresql://user:pass@host:26257/attendance_system?sslmode=verify-full"
  echo "   (local example) postgresql://root@localhost:26257/attendance_system?sslmode=disable"
  echo "   Leave blank and press Enter to use the LOCAL database."
  printf "   Connection string: "
  read -r DBURL
  if [ -z "$DBURL" ]; then DBURL="postgresql://root@localhost:26257/attendance_system?sslmode=disable"; fi
  DBSSL=false
  if echo "$DBURL" | grep -qi "cockroachlabs.cloud"; then DBSSL=true; fi
  SESSION=$(openssl rand -hex 24 2>/dev/null || echo "ap-secret-$(date +%s)")
  cat > .env <<EOF
# Attendance Pro - generated by the one-click installer
DATABASE_URL=$DBURL
DB_SSL=$DBSSL
PORT=3000
SESSION_SECRET=$SESSION
ADMIN_USERNAME=admin
ADMIN_EMAIL=admin@attendance.local
ADMIN_PASSWORD=Admin@1234
EOF
  echo "    OK - .env created"
fi

# 4. Database + start
echo "[4/4] Setting up database..."
npm run db:init || { echo "[X] Could not create the database."; exit 1; }
npm run seed >/dev/null 2>&1 || true
echo "    OK - Database ready (admin / Admin@1234)"
chmod +x start.sh 2>/dev/null || true
echo ""
echo "================================================"
echo "   INSTALLATION COMPLETE - Starting the app!"
echo "================================================"
sleep 1
./start.sh