@echo off
setlocal EnableDelayedExpansion
title Attendance Pro - Installer
chcp 65001 >nul
echo.
echo   ================================================
echo      ATTENDANCE PRO - ONE CLICK INSTALLER
echo      Your high-class attendance system
echo   ================================================
echo.

rem ---------- 1. Check Node.js ----------
echo   [1/4] Checking Node.js...
where node >nul 2>nul
if %errorlevel% neq 0 (
  echo.
  echo   [X] Node.js is NOT installed.
  echo       Please install Node.js 18 or newer from https://nodejs.org
  echo       then run Install.bat again.
  echo.
  pause
  exit /b 1
)
for /f "delims=" %%v in ('node -v') do set NODEV=%%v
echo       OK - Node.js !NODEV! found

rem ---------- 2. Install dependencies ----------
echo.
echo   [2/4] Installing dependencies (this may take a minute)...
call npm install --no-audit --no-fund
if %errorlevel% neq 0 (
  echo.
  echo   [X] npm install failed. Check your internet connection.
  pause
  exit /b 1
)
echo       OK - Dependencies installed

rem ---------- 3. Configure database ----------
echo.
echo   [3/4] Database configuration
if exist ".env" (
  echo       OK - .env found. Keeping existing configuration.
) else (
  echo.
  echo       Enter your CockroachDB connection string.
  echo       ^(cloud example^) postgresql://user:pass@host:26257/attendance_system?sslmode=verify-full
  echo       ^(local example^) postgresql://root@localhost:26257/attendance_system?sslmode=disable
  echo       Leave blank and press Enter to use the LOCAL database.
  echo.
  set /p DBURL="       Connection string: "
  if "!DBURL!"=="" set DBURL=postgresql://root@localhost:26257/attendance_system?sslmode=disable
  set DBSSL=false
  echo !DBURL! | findstr /i "cockroachlabs.cloud" >nul && set DBSSL=true
  (
    echo # Attendance Pro - generated by the one-click installer
    echo DATABASE_URL=!DBURL!
    echo DB_SSL=!DBSSL!
    echo PORT=3000
    echo SESSION_SECRET=ap-!random!!random!!random!!random!!random!
    echo ADMIN_USERNAME=admin
    echo ADMIN_EMAIL=admin@attendance.local
    echo ADMIN_PASSWORD=Admin@1234
  ) > ".env"
  echo       OK - .env created
)

rem ---------- 4. Create database + shortcuts + start ----------
echo.
echo   [4/4] Setting up database and desktop shortcut...
call npm run db:init
if %errorlevel% neq 0 (
  echo.
  echo   [X] Could not create the database. Please check the connection
  echo       string and that your cluster is reachable.
  pause
  exit /b 1
)
call npm run seed >nul 2>nul
echo.       OK - Database ready ^(admin / Admin@1234^)

rem Create a desktop shortcut so it feels like a real installed app
powershell -NoProfile -Command ^
 "$s=New-Object -ComObject WScript.Shell; $d=[Environment]::GetFolderPath('Desktop'); $l=$s.CreateShortcut((Join-Path $d 'Attendance Pro.lnk')); $l.TargetPath='%~dp0start.bat'; $l.WorkingDirectory='%~dp0'; $l.Description='Attendance Pro - high-class attendance system'; $l.IconLocation='%~dp0public\icon-192.png'; $l.Save()" >nul 2>nul
echo       OK - Desktop shortcut "Attendance Pro" created

echo.
echo   ================================================
echo      INSTALLATION COMPLETE - Starting the app!
echo   ================================================
echo.
timeout /t 2 /nobreak >nul
call "%~dp0start.bat"
endlocal